# if you have multiple (e.g., 4) GPUs, you can specify some of them(e.g. 0, 1, 2) or all of them (e.g., all)
cuda_devices: 0,1  # specify visible GPU device. If you have multiple GPUs, you can specify some of them (e.g. 0, 1, 2) or all of them (e.g., all)
data_dir: ./data  # data directory

# Attention! ALL paths must be relative to the config file!
preprocess: cfgs/preprocess_cfg.yml  # preprocess config
stage1: cfgs/stage1_cfg.yml  # stage1 config
stage2: cfgs/stage2_cfg.yml  # stage2 config
type: cfgs/type_cfg.yml  # type config